// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/user/register","parentId":"1","id":"3"},"4":{"path":"/","redirect":"/my_chart","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/add_chart_async","name":"智能分析","icon":"projectTwoTone","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/image_analysis","name":"图片分析","icon":"fileImageTwoTone","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/text_analysis","name":"文字识别","icon":"fileTextTwoTone","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"/my_chart","name":"我的图表","icon":"pieChartTwoTone","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"*","layout":false,"id":"10"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__User__Register__index" */'@/pages/User/Register/index.tsx')),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__AddChartAsync__index" */'@/pages/AddChartAsync/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__AddImage__index" */'@/pages/AddImage/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__TextAnalysis__index" */'@/pages/TextAnalysis/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__MyChart__index" */'@/pages/MyChart/index.tsx')),
'9': React.lazy(() => import( './EmptyRoute')),
'10': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'D:/frontEnd/BI/xnbi-frontend/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'D:/frontEnd/BI/xnbi-frontend/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
