// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@umijs/renderer-react';
export type {  History } from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/frontEnd/BI/xnbi-frontend/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
export const useServerInsertedHTML: Function = () => {};
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'D:/frontEnd/BI/xnbi-frontend/src/.umi/plugin-access';
export { Provider, useModel } from 'D:/frontEnd/BI/xnbi-frontend/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/frontEnd/BI/xnbi-frontend/src/.umi/plugin-request';
// plugins types.d.ts
export * from 'D:/frontEnd/BI/xnbi-frontend/src/.umi/plugin-access/types.d';
export * from 'D:/frontEnd/BI/xnbi-frontend/src/.umi/plugin-antd/types.d';
export * from 'D:/frontEnd/BI/xnbi-frontend/src/.umi/plugin-layout/types.d';
export * from 'D:/frontEnd/BI/xnbi-frontend/src/.umi/plugin-request/types.d';
