// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import ProjectTwoTone from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/ProjectTwoTone';
import FileImageTwoTone from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/FileImageTwoTone';
import FileTextTwoTone from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/FileTextTwoTone';
import PieChartTwoTone from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/PieChartTwoTone';
export default { ProjectTwoTone, FileImageTwoTone, FileTextTwoTone, PieChartTwoTone };
