// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
