// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import BarChartOutlined from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import ProjectTwoTone from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/ProjectTwoTone';
import FileImageTwoTone from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/FileImageTwoTone';
import PieChartTwoTone from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/PieChartTwoTone';
import CrownOutlined from 'D:/frontEnd/BI/xnbi-frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { BarChartOutlined, ProjectTwoTone, FileImageTwoTone, PieChartTwoTone, CrownOutlined };
